# Generated by Django 4.2.7 on 2023-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedataset',
            name='image',
            field=models.ImageField(upload_to='imagedataset/'),
        ),
        migrations.AlterField(
            model_name='imageinput',
            name='image',
            field=models.ImageField(upload_to='imageinput/'),
        ),
    ]
