# Generated by Django 4.2.7 on 2023-11-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imagedataset_image_alter_imageinput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedataset',
            name='image',
            field=models.ImageField(upload_to='dataset/'),
        ),
        migrations.AlterField(
            model_name='imageinput',
            name='image',
            field=models.ImageField(upload_to='inputimage/'),
        ),
    ]
