# Generated by Django 4.2.7 on 2023-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imageinput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinput',
            name='image',
            field=models.ImageField(default='../media/defaultimage/defaultimage.jpg', upload_to='inputimage/'),
        ),
    ]
