# Generated by Django 4.2.7 on 2023-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_imageinput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinput',
            name='image',
            field=models.ImageField(upload_to='inputimage/'),
        ),
    ]
