# Generated by Django 4.2.7 on 2023-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_imageinput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinput',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inputimage/'),
        ),
    ]
