# Generated by Django 4.2.7 on 2023-11-08 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_imageinput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedataset',
            name='image',
            field=models.FileField(null=True, upload_to='dataset/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='imageinput',
            name='image',
            field=models.ImageField(null=True, upload_to='inputimage/'),
        ),
    ]
