# Generated by Django 4.2.7 on 2023-11-09 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_imagedataset_image_alter_imageinput_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedataset',
            name='image',
            field=models.ImageField(null=True, upload_to='dataset/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
