# Generated by Django 4.2.7 on 2023-11-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_imagedataset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedataset',
            name='image',
            field=models.ImageField(null=True, upload_to='dataset/'),
        ),
    ]
