# Generated by Django 4.2.7 on 2023-11-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_imagedataset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedataset',
            name='similiarity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
